### ISSUE TITLE
Java version detection within https://github.com/nikku/camunda-playground fails

### ISSUE THREAD

**Issue by FlackMonkey** [nikku/run-camunda#6]
Hi! I try to run latest https://github.com/nikku/camunda-playground and run-camunda fails to detect java lib. 
Basically architecture checking fails: run-camunda looks for **arm64** and I have **amd64**

`$ npx camunda-playground diagram.bpmn`

`Camunda not running yet, fetching and starting it
Starting Camunda...Error: ENOENT: could not find /usr/lib/jvm/java-17-openjdk-arm64/bin/java
    at exec (/home/alx/.npm/_npx/05ff59e0ca70dbf5/node_modules/run-camunda/camunda.js:70:11)
    at runCamunda (/home/alx/.npm/_npx/05ff59e0ca70dbf5/node_modules/run-camunda/camunda.js:122:25)
    at startCamunda (/home/alx/.npm/_npx/05ff59e0ca70dbf5/node_modules/run-camunda/camunda.js:204:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async run (/home/alx/.npm/_npx/05ff59e0ca70dbf5/node_modules/camunda-playground/lib/cli.js:76:5)`

__Environment__

- Ubuntu 22.04 LTS (5.15.0-40-generic)
- AMD Ryzen 7 5800H
- uname -m -> x86_64
- npm 8.13.2

**Comment by nikku** [comment]
Can you excecute Java? 

```
/usr/lib/jvm/java-17-openjdk-arm64/bin/java -version
```

It says that java is not available there, despite being configured (likely via PATH, symlink or JAVA_HOME).

**Comment by FlackMonkey** [comment]
@nikku seems all-of-a-sudden in rest of places, JAVA_HOME was redefined before execution. nevertheless system raw settings were pointed to wrong "arm64" sdk path.
Thank you!

I'm closing bug
